---
title: "getSd"
author: "LEE SANGIN"
date: "2017년 5월 1일"
output: html_document
---

####**전체 표준편차 구하기**

  * 전체 표준편차 구할때 사용
      - 부분군 크기가 2이상일 때: sdOverAll()
      - 부분군 크기가 1일 때 : sdOverAll2()
      
  * 군내 표준편차 > 합동표준편차
      - getSp

#####**sdOverAll**

  * 함수 명: sdOverAll(split, rowSplit, colSplit, N, mean, na.rm =FALSE, c4 = 1)

  * Variables:  
    -	split : 사용 데이터 셋(dataframe)
    -	rowSplit: nrow(split) 
    -	colSplit: ncol(split) 
    - N: 전체 표본갯수
    - mean: 전체 평균
    - na.rm: TRUE시 데이터셋의 NA값 제거 후 분석(default = FALSE)
    - c4: c4값
    

#####**함수 작동원리**  
  
1. 분자구하기(=subpow)  

```
  subpow <- 0
  for(i in 1:rowSplit){
    for(j in 1:colSplit){
      subpow <- subpow + (split[i,j]-mean)^2
    }
  }
```
2. 총 표준편차 구하기  

```
  overallBefore <- sqrt(subpow/(N-1))
  result<- overallBefore/c4
```
***

#####**sdOverAll2**

  * 함수 명: sdOverAll2(split, rowSplit, colSplit, N, mean, na.rm =FALSE, c4 = 1)

  * Variables:  
    -	split : 사용 데이터 셋(dataframe)
    -	rowSplit: nrow(split) 
    -	colSplit: ncol(split) 
    - N: 전체 표본갯수
    - mean: 전체 평균
    - na.rm: TRUE시 데이터셋의 NA값 제거 후 분석(default = FALSE)
    - c4: c4값

#####**함수 작동원리**  
  
1. 분자구하기(=subpow)  

```
  subpow <- 0
  for(i in 1:rowSplit){
    for(j in 1:colSplit){
      subpow <- subpow + (split[i,j]-mean)^2
    }
  }
```
2. 총 표준편차 구하기  

```
  overallBefore <- sqrt(subpow/N-1)
  result<- overallBefore/c4
```
***

#####**getSp**

  * 함수 명: getSp(split, rowSplit, colSplit, N, group)

  * Variables:  
    -	split : 사용 데이터 셋(dataframe)
    -	rowSplit: nrow(split) 
    -	colSplit: ncol(split) 
    - N: 전체 표본갯수
    - group: 부분군 갯수

#####**함수 작동원리**  
  
1. 분자구하기(=subpow)  

```
  n <- N / group #n = 군내 데이터 갯수
  subpow <- 0
  for(i in 1:rowSplit){
    for(j in 1:colSplit){
      subpow <- subpow + (split[i,j] - split[i,colSplit+1])^2
    }
  }
```
2. 총 표준편차 구하기  

```
  sp <- subpow/(group*(n-1))
```
