---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r global, include=FALSE}
library(nycflights13)
library(dplyr)
library(shiny)
library(ggplot2)
library(leaflet)

flights <- as.data.frame(flights)
weather <- as.data.frame(weather)
airports <- as.data.frame(airports)

#flights와 weather결합 (fw = flights + weather)

fw <- left_join(flights, weather, by = c("origin", "time_hour"))

#필요없는 변수 제거
fw <- subset(fw, select = -c(year.y,month.y,day.y,hour.y,pressure))
#### NA 처리는 우선 제거하는걸로(dep_delay) > 이거 더 나은 처리방법 필요!!
fw <- fw %>%filter(!is.na(dep_delay))
#이름 바꾸고
names(fw)[c(1,2,3,17)] <- c("year","month","day","hour")
# origin factor
fw$origin <- as.factor(fw$origin)
# 12-2 : winther, 3-5 : spring, 6-8 : summer, 9-11 : fall
fw <- fw %>% mutate(season = ifelse(month == 12 | month ==1 | month ==2,"winter",
                              ifelse(month==3 | month==4 | month ==5,"spring",
                                     ifelse(month==6 | month ==7 |
                                              month==8,"summer",
                                            ifelse(month==9 | month ==10 | 
                                                     month ==11,"fall",NA)))))
# season factor화
fw$season <- as.factor(fw$season)




#####아 이것도 일단 그냥 0 이하면 delay 기준 못잡겠다.
fw <- fw %>% mutate(checkDelay = ifelse(dep_delay >0, "delayed","ontime"))

```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("originVar", label = "Select Origins",
            levels(as.factor(fw$origin)))
selectInput("seasonVar", label = "Select Seasons",
            levels(as.factor(fw$season)))

```

```{r}
dataLocation <- airports %>%
  filter(faa == "JFK" | faa == "LGA" | faa == "EWR") %>%
  select(c(faa,name, lat,lon))

leaflet(data = dataLocation) %>%
  addTiles() %>%
  addMarkers(lng=~lng, lat=~lat, label=~name)

```
Row
-----------------------------------------------------------------------

### Map
```{r}
dataLocation <- airports %>%
  filter(faa == "JFK" | faa == "LGA" | faa == "EWR")

reactive({
if(input$originVar==dataLocation[1,1]){
  lng <- dataLocation[1,4] ; lat <- dataLocation[1,3]
  popup <- dataLocation[1,2]
}else if(input$originVar == dataLocation[2,1]){
  lng <- dataLocation[2,4] ; lat <- dataLocation[2,3]
  popup <- dataLocation[2,2]
}else{
  lng <- dataLocation[3,4] ; lat <- dataLocation[3,3]
  popup <- dataLocation[3,2]
}
#   print(lng)
# print(lat)
# print(popup)
#   
      leaflet() %>%
    addTiles() %>%
    addMarkers(lng=lng, lat=lat, popup=popup)
})

# reactive({
    # leaflet() %>%
    # addTiles() %>%
    # addMarkers(lng=lng, lat=lat, popup=popup)
# 
# })
```

<!-- ```{r} -->
<!-- # reactive({ -->
<!-- # renderLeaflet({ -->
<!-- #   leaflet() %>% -->
<!-- #     addTiles() %>% -->
<!-- #     addMarkers(lng=lng, lat=lat, popup=popup) -->
<!-- # }) -->

<!-- # leafletOutput('map') -->
<!-- # }) -->

<!-- ``` -->

### Top Airlines (pie chart)

```{r}

```

Row
-----------------------------------------------------------------------

### chartA

```{r}

renderPlot({
datat <- fw %>% filter(origin==input$originVar & season ==input$seasonVar)

datat2 <- datat %>% group_by(hour) %>% summarise(Mean = mean(visib,na.rm = T)) %>% as.data.frame()
ggplot(datat2 , aes(x = hour,y = Mean, group =1, colour = "violet")) + geom_line() + geom_point()

})
```


### chartB

```{r}
renderPlot({
datat <- fw %>% filter(origin==input$originVar & season ==input$seasonVar)

datat2 <- datat %>% group_by(hour) %>% summarise(Mean = mean(wind_speed,na.rm = T)) %>% as.data.frame()
ggplot(datat2 , aes(x = hour,y = Mean, group =1, colour = "violet")) + geom_line() + geom_point()

})
```
